@accesstoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6InVzZXIiLCJsYXN0X25hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiIkMmIkMTAkWG50RjhsQVFKTVB0V1ZqbXYvRmJUdWRtQzMyOE5haUNVLmZUZHJ5NkdRMGxiZUdIWXdraU8iLCJpYXQiOjE3MTE3ODMxMzUsImV4cCI6MTcxMTgwMTEzNX0.JsZRKZv4j1hJ1igJCh7bU2Pu83fcARJ9MHILUkhmr5s


POST http://127.0.0.1:3000/api/user/login
Accept: application/json
Content-Type: application/json

{
    "firstName" : "user",
    "password" : "user"
}

 
###

POST http://127.0.0.1:3000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accesstoken}}

{
    "firstName" : "thientm2thientm21",
    "lastName" : "thientm2",
    "password" : "thientm2thientm2"
}



###
GET http://127.0.0.1:3000/api/user
Authorization: Bearer {{accesstoken}}

###

GET http://127.0.0.1:3000/api/user/3
Authorization: Bearer {{accesstoken}}
